baseURL = 'https://morganbye.com/'
title = 'Morgan Bye'
copyright = 'CC BY-SA 4.0'
defaultContentLanguage = 'en'
languageCode = 'en-ca'
languageName = 'English'
theme = 'morganbye-com_theme'
enableRobotsTXT = true


#-------------------------------
# Menus
#-------------------------------

# Main Menu
[menu]

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Blog'
pageRef = '/posts/'
weight = 20

[[menu.main]]
parent = 'Blog'
name = 'All posts'
pageRef = '/posts/'
weight = 21

[[menu.main]]
parent = 'Blog'
name = 'Daily blog'
pageRef = '/tags/blog/'
weight = 22

[[menu.main]]
parent = 'Blog'
name = 'Annual reviews'
pageRef = '/tags/annual-review/'
weight = 23

[[menu.main]]
name = 'Tech'
pageRef = '/tags/technology/'
weight = 30

[[menu.main]]
name = 'Science'
pageRef = '/tags/science/'
weight = 40
hasChildren = true

[[menu.main]]
parent = 'Science'
name = 'Essays'
pageRef = '/tags/long-form/'
weight = 41

[[menu.main]]
parent = 'Science'
name = 'EPR toolbox'
pageRef = '/tags/eprtoolbox/'
weight = 42

[[menu.main]]
name = 'About'
pageRef = '/about.html'
weight = 50


# Footer Menu
[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Projects"
url = "/projects/"
weight = 2

[[menu.footer]]
name = "Posts"
url = "/posts/"
weight = 3

[[menu.footer]]
name = "About Me"
url = "/about/"
weight = 4


#-------------------------------
# Call to action button
#-------------------------------

[params.cta_button]
enable = true
cta_button_link = "/contact/"
cta_button_text = "Get in touch"


#-------------------------------
# Logo and theme
#-------------------------------

[params]
logo = "assets/img/logos/morgan_trans.png"
logo_dark = "assets/img/logos/morgan_white.png"
description = "MORGAN BYE"
color_scheme = "auto" # auto, light, dark


#-------------------------------
# Author
#-------------------------------

[params.author]
author_name = "Morgan Bye"
author_avatar = "https://pbs.twimg.com/profile_images/1388207423702372354/KutsB7sU_400x400.jpg"


#-------------------------------
# Hero Settings
#-------------------------------

[params.hero]
enable = true
hero_title = "Bringing AI into the real world..."
hero_description = "Leveraging my expertise, I'm here to collaborate with you on bringing custom AI solutuions into the real world. Together, let's optimize this planet!"

[params.hero_logos]
enable = true

[[params.hero_logo_image]]
image_alt = "Boeing Logo"
image_url = "https://morganbye.com/assets/icons/boeing.png"

[[params.hero_logo_image]]
image_alt = "Bombardier Logo"
image_url = "https://morganbye.com/assets/icons/bbd_new.png"

[[params.hero_logo_image]]
image_alt = "Air Canada Logo"
image_url = "https://morganbye.com/assets/icons/ac.png"

[[params.hero_logo_image]]
image_alt = "BDC Logo"
image_url = "https://morganbye.com/assets/icons/bdc.png"

[[params.hero_logo_image]]
image_alt = "Japanese Airlines Logo"
image_url = "https://morganbye.com/assets/icons/jal.png"

[[params.hero_logo_image]]
image_alt = "BC Cancer Logo"
image_url = "https://morganbye.com/assets/icons/bc_cancer.png"

[[params.hero_logo_image]]
image_alt = "Loblaws Logo"
image_url = "https://morganbye.com/assets/icons/lcl.png"

[[params.hero_logo_image]]
image_alt = "BRP Logo"
image_url = "https://morganbye.com/assets/icons/brp.png"

[[params.hero_logo_image]]
image_alt = "MDA Space Logo"
image_url = "https://morganbye.com/assets/icons/mda.png"


#-------------------------------
# Slider Featured Settings
#-------------------------------

[params.featured]
enable = true
featured_title = "Top articles"
featured_description = "Don't know where to start? Here's some of my most popular writing..."


#-------------------------------
# Projects Settings
#-------------------------------

[params.projects]
enable = true
projects_title = "Selected projects"
projects_description = "Here are some of the best projects I've worked on..."


#-------------------------------
# Testimonials Section
#-------------------------------

[params.testimonials]
enable = true
testimonials_intro = "Don't take my word for it"
testimonials_title = "See what it's like to work with me..."
testimonials_info = ""

[[params.testimonial_item]]
name = "Leila Sahabejamee"
image = "https://morganbye.com/assets/testimonials/leila.jpg"
designation = "Director of Product Management"
title = "Standout talent"
content = "Morgan has a unique talent to think outside the box and grasp concepts most find difficult. His knowledge of Google Cloud and aviation big data is excellent. He was always keen and willing to learn new technology with a very positive attitude toward work."

[[params.testimonial_item]]
name = "Bimla Shelley"
image = "https://morganbye.com/assets/testimonials/bimla.jpg"
designation = "Senior Product Owner"
title = "Incredible knowledge"
content = "...the moment I see your name in a meeting, I sit back knowing you will come up with solutions that of best interests of us, it's incredible Morgan what you have contributed towards this project."

[[params.testimonial_item]]
name = "Andrew Couzens"
image = "https://morganbye.com/assets/testimonials/andrew.jpg"
designation = "DevOps Engineer"
title = "Any time, any project"
content = "Morgan exemplifies the core tenants of DevOps and more... be it his detail oriented delivery, thirst for knowledge, excellent teaching ability, architecture and design capabilities, or the superb documentation he produces... I'd gladly work with him any time, on any project and would highly recommend him to anyone. "


#-------------------------------
# FAQ
#-------------------------------

[params.faq]
enable = true
faq_intro = "Need some answers?"
faq_title = "Frequently asked questions"

[[params.faq_item]]
title = "What distinguishes you from other developers?"
description = "I've built data pipelines across 3 continents at petabyte scales, for over 15 years. But the data doesn't matter if we don't solve the human problems first - an AI solution that nobody uses is worthless."

[[params.faq_item]]
title = "Are the robots going to kill us all?"
description = "Not any time soon. At least not in the way that you've got imagined thanks to the Terminator movies. Sure somebody with a DARPA grant is always going to strap a knife/gun/flamethrower on the side of a robot - but just like in Dr.Who - right now, that robot will struggle to even get out of the room, let alone up some stairs."

[[params.faq_item]]
title = "But AI is going to steal my job, right?"
description = "A year ago, the whole world was convinced that AI was going to steal their job. Now, the reality is that most people are thinking 'I wish this POC at work would go a bit faster to scan these PDFs'."

[[params.faq_item]]
title = "When am I going to get my self-driving car?"
description = "Humans are complicated. If we invented driving today - there's NO WAY IN HELL we'd let humans do it. They get distracted. They text their friends. They drink. They make mistakes. But the reality is, all of our streets, cities (and even legal systems) have been built around these limitations. It would be surprisingly easy to build self-driving cars if there were no humans on the road. But today no one wants to take liability. If a self-driving company kills someone, who's responsible? The manufacturer? The insurance company? The software developer?"


#-------------------------------
# Blog Section
#-------------------------------

[params.blog]
enable = true
blog_intro = "Want the latest from my personal life?"
blog_title = "Here's the most recent from the blog"


#-------------------------------
# Author Section Settings
#-------------------------------

[params.author_section]
enable = true
author_section_title = "Hi there 👋 ! I'm Morgan, AI pro & certified cat herder."
author_section_description = "When I'm not crafting AI solutions for the business supply chain, you can catch me sipping coffee, training to try and get my half-marathon under 2 hours or just out on my bike"
author_section_image = "https://pbs.twimg.com/profile_images/1388207423702372354/KutsB7sU_400x400.jpg"
author_section_image_alt = "Morgan Bye"
author_section_button_text = 'Reach out and say hello'
author_section_button_link = "/contact"


#-------------------------------
# Footer Settings
#-------------------------------

[[params.social]]
icon = "fa-brands fa-linkedin"
name = "LinkedIn"
link = "https://linkedin.com/in/morganbye"

[[params.social]]
icon = "fa-brands fa-github"
name = "Github"
link = "https://github.com/morganbye"

[[params.social]]
icon = "fa-brands fa-x-twitter"
name = "Twitter"
link = "https://twitter.com/morganbye"

[[params.social]]
icon = "fa-brands fa-spotify"
name = "Spotify"
link = "https://open.spotify.com/user/morganbye"

[[params.social]]
icon = "fa-brands fa-lastfm"
name = "Last FM"
link = "https://www.last.fm/user/morganbye"

[[params.social]]
icon = "fa-brands fa-strava"
name = "Strava"
link = "https://www.strava.com/athletes/28881016"


#-------------------------------
# Mailing list
#-------------------------------

# [params.mailchimp]
# enable = true
# mailchimp_title = "Stay inspired weekly 📬 Your friendly dose of tips & insights!"
# mailchimp_description = "Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox."
# mailchimp_identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp"
# mailchimp_input_text = "Your email address"


#-------------------------------
# Contact Settings
#-------------------------------

# Formspree
[params.contact]
email = "myyrappb"
recaptcha_key = "6LfFW-YpAAAAAOYY61fTomT3Cb1cy9fCCVINir6J"


#-------------------------------
# Comment Section (Disqus)
#-------------------------------

[params.disqus]
enable = true
disqusShortname = "morganbye-com"

#-------------------------------
# Misc
#-------------------------------

[taxonomies]
tag = "tags"
category = "categories"


[pagination]
  disableAliases = false
  pagerSize = 10
  path = 'page'


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.extensions]
      footnote = true
      strikethrough = true
      table = true

    [markup.goldmark.parser.attribute]
      block = true

  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    lineNos = true
    style = 'vim'
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
